### ISSUE TITLE
Would be nice to display hyperlinked URL or at least clickable link after upload

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Platform/nb_anacondacloud#17] opened 2016-03-02 16:11 UTC
After I've clicked on the upload icon I'd like to see my notebook on Anaconda Repository.  A clickable URL or a clickable link to it would be a very useful addition.  Right now I have to manually navigate to my account and find the notebook.

**Comment by bollwyvl** [comment] 2016-04-20 16:19
This is reflected two ways:

A "visit" button appears for any notebook that has been published previously:
![cloud](https://cloud.githubusercontent.com/assets/45380/14682032/bc496226-06f1-11e6-99b7-4b455dc18be4.png)

Would a [different icon](https://fortawesome.github.io/Font-Awesome/icons/) be better than the cloud?

Also in the publish dialog, the full URL is shown:
![dialog](https://cloud.githubusercontent.com/assets/45380/14682054/d62f45fc-06f1-11e6-90e0-a807d4e7a52e.png)

Short of keeping the dialog open, I can't think of an unobtrusive way to show this more clearly...

**Comment by damianavila** [comment] 2016-04-20 16:25
I think the issue is enough well covered by the current implementation... unless @ijstokes make some more specific comments on this, I would close it as is.

**Closed as completed** 2017-04-17 18:01 UTC
Labels: enhancement
